Fix pickle error in multi-GPU evaluation
Use functools.partial instead of local function definition to avoid
AttributeError: Can't pickle local object 'worker_fn_improved.<locals>.collate_fn'